#!/usr/bin/env bash

set -eu

TEMP_GCROOT=/tmp/nixosApplier-tcc

if [ -v APPLY_NODE ]; then
    {
        CMD="$1"; shift
        case "$CMD" in
            ping)
                echo $SUDO_PASSWORD | ssh -t $APPLY_NODE sudo -S systemd-inhibit true && echo pong
            ;;
            logs)
                echo $SUDO_PASSWORD | ssh -t $APPLY_NODE sudo -S systemd-inhibit journalctl -f
            ;;
            run)
                ssh -t $APPLY_NODE "$@"
            ;;
            *)
                echo "Mandando dados da geração"
                nix-copy-closure --to $APPLY_NODE $TEMP_GCROOT
                echo "Aplicando geração"
                echo $SUDO_PASSWORD | ssh -t $APPLY_NODE sudo -S systemd-inhibit  $(realpath $TEMP_GCROOT)/bin/switch-to-configuration "$CMD" "$@"
            ;;
        esac
    } 2>&1 | while read line; do
        echo "[$APPLY_NODE - "$*"] $line"
    done
else
    case "$1" in
        ping|run)
            true
        ;;
        logs)
            printf "senha sudo: "
            read -s password
            export SUDO_PASSWORD=$password
        ;;
        *)
            printf "senha sudo: "
            read -s password
            export SUDO_PASSWORD=$password
            nix build '.#nixosApplier' -o $TEMP_GCROOT --show-trace
        ;;
    esac
    for node in 192.168.0.10{1,2,3}; do
        APPLY_NODE="$node" "$0" "$@" &
    done
    wait $(jobs -p)
    echo "Deploy finalizado"
fi

