version: "3.9"
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: example
      LDAP_BASE_DN: dc=example,dc=com
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: password
      DISABLE_CHOWN: "true"
      LDAP_TLS: "false"
      LDAP_SEED_INTERNAL_LDIF_PATH: "/forumsys.ldif"
    ports:
      - 389:389
      - 636:636
    volumes:
    - ./ldif/forumsys.ldif:/forumsys.ldif
    command: --loglevel debug
    hostname: ldap-server
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "rescue"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "openldap:rescue"
    depends_on:
      - openldap
