version: 3.9
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      - LDAP_ORGANIZATION=example
      - LDAP_DOMAIN=example.com
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_ADMIN_PASSWORD=password
    ports:
      - 389:389
      - 636:636
    volumes: ./seed.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif \
